name: Deploy to gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v3

      - name: Install and build 🔧
        run: |
          yarn install
          yarn build
          cd dist
          touch .nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app/dist
          branch: gh-pages
          clean-exclude: |
            .nojekyll